apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    trustDomain: example.org
  values:
    global:
      hub: docker.io/istio
      tag: 1.14.1
      imagePullPolicy: "IfNotPresent"
      imagePullSecrets:
        - secret-registry
    # This is used to customize the sidecar template
    sidecarInjectorWebhook:
      templates:
        spire: |
          spec:
            containers:
            - name: istio-proxy
            volumes:
            - name: workload-socket
              csi:
                driver: "csi.spiffe.io"
  components:
    pilot:
      k8s:
        env:
          # Disable istiod CA Sever functionality
          - name: ENABLE_CA_SERVER
            value: "true"
          # Check that istio-agent's namespace and service account match the ones in the JWT token presented in the connection
          - name: PILOT_ENABLE_XDS_IDENTITY_CHECK
            value: "true"
    ingressGateways:
     - name: istio-ingressgateway
       enabled: true
       label:
         istio: ingressgateway
       k8s:
         overlays:
           - apiVersion: apps/v1
             kind: Deployment
             name: istio-ingressgateway
             patches:
               - path: spec.template.spec.volumes.[name:workload-socket]
                 value:
                   name: workload-socket
                   csi:
                     driver: "csi.spiffe.io"
